### ISSUE TITLE
Not seeing output fasta file in output file

### ISSUE THREAD

**Issue by Sicheng-Shu** [smarini/tardis-phylogenetics#3]
Hi!
I need some help with some parameter configuration for some issues I'm having when running the Tardis with my own data.

**1）**When using example data, I don't see the subsample fasta file in the output file. I don't know what's wrong with my usage? I ran it using the default parameters.

**2）**When I used my own data, first I obtained the rds file of Jukes-Cantor distances, then I input the .rds together with .fasta and metadata.csv, and the following error occurred when running tardis. I tried 2 ways run Tardis.
**GUI:**
Rscript ../bin/make.gen.R --distance C:\Temp\RtmpGwNUht/1fa92578a9ea3814f54c9109/0.rds --metadata C:\Temp\RtmpGwNUht/b2f1c48849ecf6b23618c1ae/0.csv --generation 9 --frac.new 0.05 --frac.evo 0.9 --frac.eli 0.05 --gen.size 100 --n.samples 5 --n.cores 1 --w.tem 0.5 --w.div 0.5 --seeds ../data/seeds.txt --out.dir ../shiny_output --data.set 1215.dataset --dist.opt max
Loading required package: foreach
Loading required package: rngtools
Error in xj[i] : invalid subscript type 'list'
Calls: [ -> [.data.frame
Execution halted

**Ubuntu:** partial
Command error:
  Loading required package: foreach
  Loading required package: rngtools
  Error in xj[i] : invalid subscript type 'list'
  Calls: [ -> [.data.frame
  Execution halted

Work dir:
  /mnt/d/02_Bioinformatics/Program/tardis-phylogenetics-master/work/1e/1d1f68b5a09ed4f9d98276dd50aedb

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
*** GA done.

*** sequence Final results:
   output/sequence/subsample.GA.sequence.*.fa

I don't know what the problem is, I hope you can help me answer it.

**3）**There is another usage method that I want to know if tardis can implement it. During my downsampling process, I hope to be able to use location (like country), host (like avian, swine, human), date (dd-mm-yyyy) and the sequence of the corresponding strain to achieve downsampling. I saw that the metadata.csv of the sample data only contains ID, data, and country. I wonder if it can still be achieved if additional parameters are added?
If possible, I would like to know what code input should I use to achieve analysis? By the way, I run tardis on Ubuntu, but I also use Tardis in the GUI (in the browser).

Thanks in advance!

**Comment by smarini** [comment]
Hi! Thank you for using TARDiS.

1) I run the GUI and it works fine. However, in order to use the command line version, I had to use an earlier version of NextFlow. It works fine with version 22.10.6. I had the same problem you describe with the latest version. I will look into the issue and update the readme as necessary.

2) It might be a format error...? Does it work with GUI and the example data? Does it run if you use a small subset of your data?

3) You can see the group mode as a smooth way to run TARDiS multiple times on different data subsets. So if you have several labels for your data, you could obtain the same effect by running TARDiS independently to data subsets characterized by a label. By this principle, if you have multiple labels, you can consider them combined to split the data with a finer granularity. For example, if your data are labeled as A, B, and C, but also as 1 an 2, you can consider 6 groups: A1, A2, B1, B2, C1, and C2. You can add a column with the six groups and use the group mode; or you can manually split the data into 6 groups and run TARDiS independently on each of them, and then merge the results.
